#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("sit313.Ass01.PA.Resource", IsApplication=true)]

namespace sit313.Ass01.PA
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int colorAccent = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int colorFire = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int colorFireTrans = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int colorGrey = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int colorPink = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int colorPrimaryDark = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int colorSunrise = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int fab_margin = 2131099650;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int detail = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dollars = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int exit = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int insert = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int keyborad = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int left = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int list = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int percent = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int right = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int btnBack = 2131230722;
			
			// aapt resource value: 0x7f08000d
			public const int btnCancel = 2131230733;
			
			// aapt resource value: 0x7f08000b
			public const int btnDetails = 2131230731;
			
			// aapt resource value: 0x7f080003
			public const int btnDone = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int btnInsert = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int btnKey = 2131230724;
			
			// aapt resource value: 0x7f08000a
			public const int btnLeft = 2131230730;
			
			// aapt resource value: 0x7f080006
			public const int btnList = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int btnRight = 2131230729;
			
			// aapt resource value: 0x7f080000
			public const int cash = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int comment = 2131230721;
			
			// aapt resource value: 0x7f080010
			public const int item = 2131230736;
			
			// aapt resource value: 0x7f08000c
			public const int lblAmount = 2131230732;
			
			// aapt resource value: 0x7f080008
			public const int lblDate = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int lblDateInsert = 2131230725;
			
			// aapt resource value: 0x7f08000e
			public const int lstDetail = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int value = 2131230735;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_insert = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int detail = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int detail_adapter = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int action_settings = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int title_activity_main = 2131165186;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
